package com.vijaysinghpuwar.trustkart.catalog.seed;

import com.vijaysinghpuwar.trustkart.catalog.application.CatalogChanged;
import com.vijaysinghpuwar.trustkart.catalog.domain.Brand;
import com.vijaysinghpuwar.trustkart.catalog.domain.Category;
import com.vijaysinghpuwar.trustkart.catalog.domain.ImageMatch;
import com.vijaysinghpuwar.trustkart.catalog.domain.Inventory;
import com.vijaysinghpuwar.trustkart.catalog.domain.Product;
import com.vijaysinghpuwar.trustkart.catalog.domain.ProductImage;
import com.vijaysinghpuwar.trustkart.catalog.domain.ProductOptions;
import com.vijaysinghpuwar.trustkart.catalog.domain.ProductStatus;
import com.vijaysinghpuwar.trustkart.catalog.domain.SpecDataType;
import com.vijaysinghpuwar.trustkart.catalog.domain.SpecDefinition;
import com.vijaysinghpuwar.trustkart.catalog.infra.BrandRepository;
import com.vijaysinghpuwar.trustkart.catalog.infra.CatalogFacetRepository;
import com.vijaysinghpuwar.trustkart.catalog.infra.CategoryRepository;
import com.vijaysinghpuwar.trustkart.catalog.infra.ProductRepository;
import com.vijaysinghpuwar.trustkart.catalog.infra.SpecDefinitionRepository;
import com.vijaysinghpuwar.trustkart.catalog.seed.SeedModel.CategorySeed;
import com.vijaysinghpuwar.trustkart.catalog.seed.SeedModel.ImageSeed;
import com.vijaysinghpuwar.trustkart.catalog.seed.SeedModel.ProductSeed;
import com.vijaysinghpuwar.trustkart.catalog.seed.SeedModel.SpecSeed;
import java.io.IOException;
import java.io.InputStream;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.text.Normalizer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.HexFormat;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Component;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.ObjectMapper;

/**
 * Loads the demo catalog: {@code demo/*.json} plus the researched catalog under {@code catalog/} (generated by
 * {@code scripts/catalog/build.py}; category extensions, one product file per source, and image records). Repeatable: running it any number of times leaves exactly one copy of every
 * category, spec definition, brand and product, and never overwrites a product that already exists (so
 * admin edits survive restarts). The one exception: a product that has no image gets the seed's image once one is
 * sourced. It is only invoked when {@code trustkart.demo.seed-catalog=true}.
 *
 * <p>Products are written in chunks, each in its own transaction, so the persistence context stays small (one
 * transaction for the whole catalog made every query re-check every loaded product and took minutes). A run that is
 * interrupted keeps the chunks already written; the next run finishes the job. After a complete run the seed files'
 * fingerprint is stored, and a restart with the same files skips seeding entirely.
 */
@Component
public class DemoCatalogSeeder {

    public record Result(int categoriesCreated, int productsCreated, int productsSkipped) {}

    private static final String CATALOG_CATEGORIES = "catalog/categories.json";
    private static final String CATALOG_PRODUCTS = "classpath*:catalog/products/*.json";
    private static final String CATALOG_IMAGES = "catalog/images.json";
    private static final String CATALOG_PARKED = "catalog/parked.json";

    private static final String[] SEED_FILES = {"demo/categories.json", "demo/products.json", "demo/images.json",
            CATALOG_CATEGORIES, CATALOG_IMAGES, CATALOG_PARKED};
    /** Bump when the seeding logic changes in a way that should re-run it over unchanged files. */
    private static final int SEED_LOGIC_VERSION = 1;
    private static final int CHUNK = 100;

    private static final Logger log = LoggerFactory.getLogger(DemoCatalogSeeder.class);
    private static final int BACKORDER_CAP = 0;

    private final ObjectMapper mapper;
    private final CategoryRepository categories;
    private final SpecDefinitionRepository specDefinitions;
    private final BrandRepository brands;
    private final ProductRepository products;
    private final CatalogFacetRepository facets;
    private final JdbcClient jdbc;
    private final TransactionTemplate tx;
    private final ApplicationEventPublisher events;

    public DemoCatalogSeeder(ObjectMapper mapper, CategoryRepository categories, SpecDefinitionRepository specDefinitions,
            BrandRepository brands, ProductRepository products, CatalogFacetRepository facets, JdbcClient jdbc,
            PlatformTransactionManager transactions, ApplicationEventPublisher events) {
        this.mapper = mapper;
        this.events = events;
        this.jdbc = jdbc;
        this.tx = new TransactionTemplate(transactions);
        this.categories = categories;
        this.specDefinitions = specDefinitions;
        this.brands = brands;
        this.products = products;
        this.facets = facets;
    }

    public Result seed() {
        List<CategorySeed> categorySeeds = withExtensions(
                read("demo/categories.json", SeedModel.CategoryFile.class).categories());
        List<ProductSeed> productSeeds = new ArrayList<>(read("demo/products.json", SeedModel.ProductFile.class).products());
        List<ProductSeed> catalogSeeds = catalogProducts();
        productSeeds.addAll(catalogSeeds);

        String fingerprint = fingerprint();
        if (fingerprint.equals(storedFingerprint())) {
            log.info("Demo catalog unchanged since the last complete seed ({} products); skipping", productSeeds.size());
            return new Result(0, 0, productSeeds.size());
        }

        Set<String> catalogSkus = catalogSeeds.stream().map(ProductSeed::sku).collect(Collectors.toSet());
        Map<String, ImageSeed> images = new HashMap<>(
                read("demo/images.json", new TypeReference<Map<String, ImageSeed>>() {}));
        if (new ClassPathResource(CATALOG_IMAGES).exists()) {
            images.putAll(read(CATALOG_IMAGES, new TypeReference<Map<String, ImageSeed>>() {}));
        }

        Map<String, List<SpecSeed>> effectiveSpecs = new HashMap<>();
        int[] created = {0};
        tx.executeWithoutResult(status -> {
            Map<String, Category> bySlug = new HashMap<>();
            for (int i = 0; i < categorySeeds.size(); i++) {
                upsertCategory(categorySeeds.get(i), null, i, List.of(), bySlug, effectiveSpecs, created);
            }
        });

        int[] counts = new int[3]; // created, already present, images refreshed
        for (int from = 0; from < productSeeds.size(); from += CHUNK) {
            List<ProductSeed> chunk = productSeeds.subList(from, Math.min(from + CHUNK, productSeeds.size()));
            tx.executeWithoutResult(status -> {
                Map<String, Category> bySlug = categories.findAll().stream()
                        .collect(Collectors.toMap(Category::getSlug, c -> c));
                for (ProductSeed seed : chunk) {
                    if (products.existsBySku(seed.sku())) {
                        counts[2] += refreshExisting(seed, images, catalogSkus) ? 1 : 0;
                        counts[1]++;
                    } else {
                        createProduct(seed, bySlug, effectiveSpecs, images);
                        counts[0]++;
                    }
                }
            });
        }
        tx.executeWithoutResult(status -> {
            int parked = parkProducts();
            if (parked > 0) {
                log.info("{} catalog products parked (hidden) until an official image is sourced", parked);
            }
            jdbc.sql("""
                            INSERT INTO catalog_seed_state (id, fingerprint, products) VALUES (1, :f, :n)
                            ON CONFLICT (id) DO UPDATE SET fingerprint = :f, products = :n, seeded_at = now()""")
                    .param("f", fingerprint).param("n", productSeeds.size()).update();
        });
        events.publishEvent(new CatalogChanged());
        log.info("Demo catalog seeded: {} categories created, {} products created, {} already present ({} images refreshed)",
                created[0], counts[0], counts[1], counts[2]);
        return new Result(created[0], counts[0], counts[1]);
    }

    /**
     * Existing products keep their data, but pick up replaced product images (or a first image), the seed's current
     * purchase options, and come out of parking once they are in the catalog again. Returns whether an image was
     * replaced.
     */
    private boolean refreshExisting(ProductSeed seed, Map<String, ImageSeed> images, Set<String> catalogSkus) {
        Product product = products.findWithDetailsBySlug(seed.slug()).orElse(null);
        boolean refreshed = false;
        ImageSeed image = images.get(seed.slug());
        if (product != null && image != null) {
            refreshed = product.getImages().stream().filter(i -> i.getSortOrder() == 0).findFirst()
                    .map(i -> i.replaceWith(image.large(), image.small(), image.width(), image.height(), image.alt(),
                            ImageMatch.valueOf(image.match()), image.author() + ", " + image.license(), image.filePage()))
                    .orElse(false);
            if (!refreshed && product.getSku().equals(seed.sku()) && product.getImages().isEmpty()) {
                product.addImage(toImage(image));
            }
        }
        if (product != null && product.getSku().equals(seed.sku())) {
            applyOptions(product, seed);
        }
        if (seed.sku().startsWith("TK-") && catalogSkus.contains(seed.sku())) {
            (product != null && product.getSku().equals(seed.sku()) ? Optional.of(product)
                    : products.findBySku(seed.sku())).ifPresent(Product::unpark);
        }
        return refreshed;
    }

    private String storedFingerprint() {
        return jdbc.sql("SELECT fingerprint FROM catalog_seed_state WHERE id = 1").query(String.class).optional()
                .orElse(null);
    }

    /** SHA-256 over every seed file (name and bytes) plus the seeding logic version. */
    private String fingerprint() {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            digest.update(("v" + SEED_LOGIC_VERSION).getBytes(StandardCharsets.UTF_8));
            List<Resource> files = new ArrayList<>();
            for (String path : SEED_FILES) {
                ClassPathResource r = new ClassPathResource(path);
                if (r.exists()) {
                    files.add(r);
                }
            }
            Resource[] products = new PathMatchingResourcePatternResolver().getResources(CATALOG_PRODUCTS);
            Arrays.sort(products, Comparator.comparing(r -> Objects.requireNonNullElse(r.getFilename(), "")));
            files.addAll(Arrays.asList(products));
            for (Resource file : files) {
                digest.update(Objects.requireNonNullElse(file.getFilename(), "").getBytes(StandardCharsets.UTF_8));
                try (InputStream in = file.getInputStream()) {
                    digest.update(in.readAllBytes());
                }
            }
            return HexFormat.of().formatHex(digest.digest());
        } catch (IOException | NoSuchAlgorithmException e) {
            throw new IllegalStateException("Cannot fingerprint the demo catalog", e);
        }
    }

    /** Grafts {@code catalog/categories.json} onto the demo tree before anything is written. */
    private List<CategorySeed> withExtensions(List<CategorySeed> tree) {
        if (!new ClassPathResource(CATALOG_CATEGORIES).exists()) {
            return tree;
        }
        SeedModel.CategoryExtensionFile file = read(CATALOG_CATEGORIES, SeedModel.CategoryExtensionFile.class);
        List<CategorySeed> merged = tree;
        for (SeedModel.CategoryExtension e : file.extensionsOrEmpty()) {
            int[] hits = {0};
            merged = graft(merged, e, hits);
            if (hits[0] != 1) {
                throw new IllegalStateException(CATALOG_CATEGORIES + " extends unknown category " + e.extend());
            }
        }
        List<CategorySeed> out = new ArrayList<>(merged);
        out.addAll(file.categoriesOrEmpty());
        return out;
    }

    private static List<CategorySeed> graft(List<CategorySeed> nodes, SeedModel.CategoryExtension e, int[] hits) {
        List<CategorySeed> out = new ArrayList<>(nodes.size());
        for (CategorySeed n : nodes) {
            if (n.slug().equals(e.extend())) {
                hits[0]++;
                out.add(n.extendedWith(e));
            } else {
                out.add(n.withChildren(graft(n.childrenOrEmpty(), e, hits)));
            }
        }
        return out;
    }

    /** Product files under {@code catalog/products}, in file-name order so seeding is deterministic. */
    private List<ProductSeed> catalogProducts() {
        try {
            Resource[] files = new PathMatchingResourcePatternResolver().getResources(CATALOG_PRODUCTS);
            Arrays.sort(files, Comparator.comparing(r -> Objects.requireNonNullElse(r.getFilename(), "")));
            List<ProductSeed> seeds = new ArrayList<>();
            for (Resource file : files) {
                try (InputStream in = file.getInputStream()) {
                    seeds.addAll(mapper.readValue(in, SeedModel.ProductFile.class).products());
                }
            }
            return seeds;
        } catch (IOException e) {
            throw new IllegalStateException("Cannot read " + CATALOG_PRODUCTS, e);
        }
    }

    private static ProductImage toImage(ImageSeed image) {
        return new ProductImage(image.large(), image.small(), image.width(), image.height(), image.alt(),
                ImageMatch.valueOf(image.match()), image.author() + ", " + image.license(), image.filePage(), 0);
    }

    private void upsertCategory(CategorySeed seed, Category parent, int order, List<SpecSeed> inherited,
            Map<String, Category> bySlug, Map<String, List<SpecSeed>> effectiveSpecs, int[] created) {
        Category category = categories.findBySlug(seed.slug()).orElseGet(() -> {
            created[0]++;
            return categories.save(new Category(seed.slug(), seed.name(), parent, seed.description(), order));
        });
        bySlug.put(seed.slug(), category);

        List<SpecSeed> specs = seed.specsOrEmpty();
        for (int i = 0; i < specs.size(); i++) {
            SpecSeed s = specs.get(i);
            if (!specDefinitions.existsByCategoryIdAndKey(category.getId(), s.key())) {
                specDefinitions.save(new SpecDefinition(category, s.key(), s.label(), SpecDataType.valueOf(s.type()),
                        s.unit(), Objects.requireNonNullElse(s.group(), "Specifications"),
                        Boolean.TRUE.equals(s.filterable()), !Boolean.FALSE.equals(s.comparable()), i));
            }
        }
        List<SpecSeed> effective = new ArrayList<>(inherited);
        effective.addAll(specs);
        effectiveSpecs.put(seed.slug(), effective);

        List<CategorySeed> children = seed.childrenOrEmpty();
        for (int i = 0; i < children.size(); i++) {
            upsertCategory(children.get(i), category, i, effective, bySlug, effectiveSpecs, created);
        }
    }

    private void createProduct(ProductSeed seed, Map<String, Category> categoriesBySlug,
            Map<String, List<SpecSeed>> effectiveSpecs, Map<String, ImageSeed> images) {
        Category category = require(categoriesBySlug.get(seed.category()), "Unknown category " + seed.category());
        validateSpecs(seed, effectiveSpecs.get(seed.category()));
        // Looked up by slug (the unique key), so "CORSAIR" and "Corsair" can never create two colliding brands.
        String brandSlug = slugify(seed.brand());
        Brand brand = brands.findBySlug(brandSlug).orElseGet(() -> brands.save(new Brand(brandSlug, seed.brand())));

        ProductStatus status = Boolean.TRUE.equals(seed.discontinued()) ? ProductStatus.DISCONTINUED : ProductStatus.ACTIVE;
        Product product = new Product(seed.sku(), seed.slug(), seed.name(), brand, category, seed.summary(),
                seed.description(), money(seed.price()), seed.compareAt() == null ? null : money(seed.compareAt()),
                Objects.requireNonNullElse(seed.warranty(), 12), seed.specs(), Objects.requireNonNullElse(seed.keywords(), ""),
                Boolean.TRUE.equals(seed.featured()), status);
        product.setSearchText(searchText(seed, category));
        applyOptions(product, seed);

        int available = seed.stock().get(0);
        int threshold = seed.stock().get(1);
        product.attachInventory(new Inventory(product, available, threshold, Boolean.TRUE.equals(seed.backorder()),
                status == ProductStatus.DISCONTINUED ? BACKORDER_CAP : available));

        ImageSeed image = images.get(seed.slug());
        if (image != null) {
            product.addImage(toImage(image));
        } else {
            log.warn("No image for demo product {}", seed.slug());
        }
        Product saved = products.save(product);

        List<String> tags = seed.collections() == null ? List.of() : seed.collections();
        for (int i = 0; i < tags.size(); i++) {
            facets.addToCollection(saved.getId(), tags.get(i), i);
        }
    }

    /** Hides seeded products listed in {@code catalog/parked.json}; they have no official image yet. */
    private int parkProducts() {
        if (!new ClassPathResource(CATALOG_PARKED).exists()) {
            return 0;
        }
        SeedModel.ParkedFile file = read(CATALOG_PARKED, SeedModel.ParkedFile.class);
        int count = 0;
        for (String sku : file.skus()) {
            count += products.findBySku(sku).map(p -> p.park() ? 1 : 0).orElse(0);
        }
        return count;
    }

    private static void applyOptions(Product product, ProductSeed seed) {
        List<ProductOptions.Group> groups = seed.options() == null ? List.of() : seed.options().stream()
                .map(g -> new ProductOptions.Group(g.name(), g.values().stream()
                        .map(v -> new ProductOptions.Value(v.label(), v.price() == null ? null : money(v.price()),
                                Boolean.TRUE.equals(v.isDefault()), v.image() == null ? null
                                        : new ProductOptions.Image(v.image().small(), v.image().large(), v.image().width(),
                                                v.image().height(), v.image().alt())))
                        .toList()))
                .toList();
        try {
            product.setOptions(groups);
        } catch (IllegalArgumentException e) {
            throw new IllegalStateException(seed.sku() + ": invalid options: " + e.getMessage(), e);
        }
    }

    private static void validateSpecs(ProductSeed seed, List<SpecSeed> definitions) {
        Map<String, SpecSeed> byKey = definitions.stream()
                .collect(Collectors.toMap(SpecSeed::key, s -> s, (a, b) -> b));
        seed.specs().forEach((key, value) -> {
            SpecSeed def = byKey.get(key);
            if (def == null) {
                throw new IllegalStateException(seed.sku() + ": spec '" + key + "' is not defined for " + seed.category());
            }
            if (!SpecDataType.valueOf(def.type()).accepts(value)) {
                throw new IllegalStateException(seed.sku() + ": spec '" + key + "' must be " + def.type());
            }
        });
    }

    private static String searchText(ProductSeed seed, Category category) {
        List<String> parts = new ArrayList<>(List.of(seed.brand()));
        for (Category c = category; c != null; c = c.getParent()) {
            parts.add(c.getName());
        }
        seed.specs().values().stream().filter(String.class::isInstance).map(String.class::cast).forEach(parts::add);
        return String.join(" ", parts);
    }

    private static BigDecimal money(String raw) {
        BigDecimal value = new BigDecimal(raw);
        if (value.scale() > 2 || value.signum() <= 0) {
            throw new IllegalStateException("Invalid demo price " + raw);
        }
        return value.setScale(2);
    }

    static String slugify(String name) {
        String ascii = Normalizer.normalize(name, Normalizer.Form.NFD).replaceAll("\\p{M}", "");
        return ascii.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+", "-").replaceAll("(^-|-$)", "");
    }

    private static <T> T require(T value, String message) {
        if (value == null) {
            throw new IllegalStateException(message);
        }
        return value;
    }

    private <T> T read(String path, Class<T> type) {
        try (InputStream in = new ClassPathResource(path).getInputStream()) {
            return mapper.readValue(in, type);
        } catch (IOException e) {
            throw new IllegalStateException("Cannot read " + path, e);
        }
    }

    private <T> T read(String path, TypeReference<T> type) {
        try (InputStream in = new ClassPathResource(path).getInputStream()) {
            return mapper.readValue(in, type);
        } catch (IOException e) {
            throw new IllegalStateException("Cannot read " + path, e);
        }
    }
}
