// Synthetic notification-retention fixture in the disposable audit DB only.
const {request}=require('/private/tmp/trustkart-audit-20260930/frontend/node_modules/@playwright/test');const {execFileSync}=require('node:child_process');const {createHash}=require('node:crypto');const fs=require('node:fs');const path=require('node:path');const root=path.resolve(__dirname,'..');const base='http://127.0.0.1:15173/api/v1';
const sql=q=>execFileSync('docker',['exec','-i','codex-trustkart-audit-postgres-1','psql','-X','-At','-v','ON_ERROR_STOP=1','-U','trustkart','-d','trustkart'],{input:q,encoding:'utf8'});
(async()=>{
 const c=await request.newContext();await c.get(base+'/auth/csrf');let state=await c.storageState();const csrf=state.cookies.find(x=>x.name==='XSRF-TOKEN').value;
 const write=async(p,data)=>{const r=await c.post(base+p,{data,headers:{'X-XSRF-TOKEN':csrf}});if(!r.ok())throw Error(await r.text());return r.status()===204?null:await r.json()};
 const products=await(await c.get(base+'/catalog/products?size=1')).json();const product=products.items[0];const rows=[];
 for(let i=0;i<3;i++){const l=await write('/wishlist/lists',{name:'Audit list '+i});await write('/wishlist/items',{productId:product.id,listId:l.id});const r=await c.get(base+'/wishlist');rows.push({check:'wishlist reads',lists:i+1,requestId:r.headers()['x-request-id'],status:r.status(),bytes:(await r.body()).length});}
 state=await c.storageState();const guest=state.cookies.find(x=>x.name==='tk_guest').value;const hash=createHash('sha256').update(guest).digest('hex');const id=Number(sql(`SELECT id FROM shopper WHERE guest_token_hash='${hash}';`).trim());if(!Number.isInteger(id))throw Error('Missing local fixture shopper');
 const fixture=`-- Synthetic UNLIMITED guest orders, no inventory commits; only for retention behavior.\nWITH inserted AS (INSERT INTO virtual_purchase(public_id,order_number,shopper_id,status,item_count,subtotal,shipping,total,wallet_mode,delivery_preset,idempotency_key,request_hash,created_at) SELECT gen_random_uuid(),'AUD-NOTIF-${id}-'||g,${id},'COMPLETED',1,1,0,1,'UNLIMITED','ADDRESS',gen_random_uuid()::text,repeat('0',64),now()-interval '8 days'-g*interval '1 minute' FROM generate_series(1,60) g RETURNING id) INSERT INTO virtual_purchase_item(purchase_id,product_id,product_slug,product_name,category_name,unit_price,quantity,line_total,stock_committed) SELECT id,${product.id},'audit-retention-fixture','Audit retention fixture','Audit',1,1,1,0 FROM inserted;`;
 fs.writeFileSync(path.join(root,'evidence/notification-fixture.sql'),fixture);sql(fixture);
 for(let i=0;i<3;i++){const r=await c.get(base+'/notifications/unread-count');rows.push({check:'60 delivered orders notification poll',poll:i+1,status:r.status(),requestId:r.headers()['x-request-id'],body:await r.json(),stored:Number(sql(`SELECT count(*) FROM notification WHERE shopper_id=${id};`).trim())});}
 const notes=await(await c.get(base+'/notifications?size=30')).json();rows.push({check:'notification pagination',returned:notes.items.length,total:notes.totalItems,size:notes.size});
 fs.writeFileSync(path.join(root,'evidence/bounded-data.json'),JSON.stringify(rows,null,2));await c.dispose();
})().catch(e=>{console.error(e);process.exit(1)});
